import "../lexer/tests/index.test";
import "../parser/tests/index.test";
import "../ast/tests/index.test";
import "../imports/tests/index.test";
import "../validator/tests/index.test";
import "../cql-emitter/tests/index.test";
import "../fhir-emitter/tests/index.test";
import "../cli/tests/run-emitter.test";
import "./regression/index.test";
