const esbuild=require('esbuild'),assert=require('node:assert/strict');
const endpoint=process.env.CRL_TEST_CDP_URL||'http://127.0.0.1:9643';
async function rpc(target,expression){const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});try{return await new Promise((r,j)=>{const timer=setTimeout(()=>j(Error('CDP timeout')),15000);ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id===1){clearTimeout(timer);r(m);}};ws.send(JSON.stringify({id:1,method:'Runtime.evaluate',params:{expression,returnByValue:true,awaitPromise:true}}));});}finally{ws.close();}}
(async()=>{
 const targets=await(await fetch(endpoint+'/json')).json();let target;
 for(const t of targets.filter(t=>t.type==='iframe')){const r=await rpc(t,"!!document.querySelector('iframe')?.contentDocument?.querySelector('.flow-svg')");if(r.result?.result?.value){target=t;break;}}
 assert(target,'open MV tree required');
 const js=esbuild.buildSync({entryPoints:['packages/crl-vscode/src/routeCardsWebview.ts'],bundle:true,write:false,format:'iife',globalName:'Cards'}).outputFiles[0].text;
 const expression=`(()=>{const document=globalThis.document.querySelector('iframe').contentDocument;${js}
 const tree=document.createElement('div'),pane=document.createElement('div');document.body.append(tree,pane);
 const svg='<svg class="flow-svg" viewBox="0 0 1200 700" width="1200" height="700">'+[0,1,2].map(i=>'<g data-flow-key="w'+i+'" data-flow-when="w'+i+'"><rect x="'+(20+i*380)+'" y="20" width="168" height="44"/></g>'+[0,1,2].map(j=>'<g data-flow-key="q'+i+j+'" data-flow-when="w'+i+'" data-flow-parent="w'+i+'" data-flow-outline="1"><rect x="'+(30+i*380)+'" y="'+(100+j*110)+'" width="150" height="34"/></g>').join('')+'<g data-flow-key="choice'+i+'" data-flow-when="w'+i+'" data-flow-parent="q'+i+'0" data-flow-outline="1"><rect x="'+(40+i*380)+'" y="460" width="130" height="30"/></g>').join('')+'</svg>';
 tree.innerHTML=svg;for(const n of tree.querySelectorAll('[data-flow-key]')){const k=n.dataset.flowKey;if(k.startsWith('q'))n.dataset.flowQuestion=JSON.stringify(['L','Q'+k.at(-1)]);if(k.startsWith('choice')){n.dataset.flowChoice=JSON.stringify({code:'yes'});n.dataset.flowChoiceFor=JSON.stringify(['L','Q0']);}}
 const original=tree.innerHTML;
 const sent=[],branchSent=[],ui=Cards.installRouteCards(tree,{postMessage:m=>sent.push(m)},()=>1),branch=Cards.installRouteCards(pane,{postMessage:m=>branchSent.push(m)},()=>1,()=>{},true);
 const payload={token:'same',label:'Shared inputs',cards:[0,1,2].map(j=>({id:'card'+j,questionNumber:j+1,ownerKey:'w0',occurrences:[0,1,2].map(i=>({ownerKey:'w'+i,criterionPaths:[[]]})),criterionPaths:[[]],library:'L',concept:'Q'+j,text:'Question '+j+'?',description:'Description',value:'Yes',determination:'True',editable:true,answerChoices:j===0?[{code:'yes',display:'Yes',selected:true}]:[]}))};
 const clone=x=>JSON.parse(JSON.stringify(x));ui.show(clone(payload));branch.show(clone(payload));
 const result={treeCards:tree.querySelectorAll('.route-card').length,questionnaireCards:pane.querySelectorAll('.route-card').length,questionnaireNumbers:[...pane.querySelectorAll('.route-card-caption')].map(n=>n.textContent),treeNumbers:[...tree.querySelectorAll('.route-card-caption')].map(n=>n.textContent),noUnneededSelector:!pane.querySelector('select')};
 const secondary=tree.querySelector('[data-owner-key="q20"]');secondary.querySelector('.route-card-edit').click();const editor=tree.querySelector('[data-owner-key="q20"] textarea');editor.value='Shared draft';editor.dispatchEvent(new document.defaultView.Event('input',{bubbles:true}));branch.draft(sent.at(-1));branch.show(clone(payload));result.secondaryDraft=pane.querySelector('textarea').value==='Shared draft'&&!pane.querySelector('.route-card-editor').hidden;
 ui.questionnaireState(true);result.badges=[...tree.querySelectorAll('.route-question-badge text')].map(n=>n.textContent);ui.questionnaireState(false);tree.querySelector('.route-questions-toggle').click();result.selectedChoices=tree.querySelectorAll('.flow-choice-selected').length;
 const variants=clone(payload);variants.token='variants';variants.cards=[{...variants.cards[0],scopeLabel:'Criterion A'},{...variants.cards[0],id:'variant',scopeLabel:'Criterion B',text:'Alternate wording?',value:'Determination: Unknown',determination:'Unknown'}];branch.show(variants);
 variants.cards[0].determination='';branch.show(variants);result.valueOnlyUnknownVisible=pane.querySelector('.route-determination-note').textContent.includes('Unknown');result.variantLabels=[...pane.querySelectorAll('option')].map(o=>o.textContent).some(t=>t.includes('Determination: Unknown'));
 result.oneVariantQuestion=pane.querySelectorAll('.route-card').length===1;result.unknownVisible=pane.querySelector('.route-determination-note').textContent.includes('Unknown');
 let select=pane.querySelector('select');select.value='variant';select.dispatchEvent(new document.defaultView.Event('change'));pane.querySelector('.route-card-edit').click();pane.querySelector('.route-card-editor button').click();result.variantTarget=branchSent.at(-1).key;
 select=pane.querySelector('select');select.value='card0';select.dispatchEvent(new document.defaultView.Event('change'));branch.result({token:'variants',key:'variant',ok:false,message:'Synthetic save failure'});select=pane.querySelector('select');select.value='variant';select.dispatchEvent(new document.defaultView.Event('change'));result.failureRetained=pane.querySelector('.route-card-status').textContent==='Synthetic save failure';
 select=pane.querySelector('select');select.value='card0';select.dispatchEvent(new document.defaultView.Event('change'));branch.result({token:'variants',key:'variant',ok:true,message:'Saved variant'});select=pane.querySelector('select');select.value='variant';select.dispatchEvent(new document.defaultView.Event('change'));result.successRetained=pane.querySelector('.route-card-status').textContent==='Saved variant';
 branch.show({...clone(payload),token:'new'});branch.result({token:'variants',key:'card0',ok:false,message:'Stale'});result.staleIgnored=![...pane.querySelectorAll('.route-card-status')].some(n=>n.textContent==='Stale');
 ui.reset();for(const n of tree.querySelectorAll('[class=""]'))n.removeAttribute('class');result.treeRestored=tree.innerHTML===original;branch.reset();tree.remove();pane.remove();return result;})()`;
 const r=await rpc(target,expression);assert(!r.result?.exceptionDetails,JSON.stringify(r));const v=r.result.result.value;
 assert.equal(v.treeCards,9);assert.equal(v.questionnaireCards,3);assert.deepEqual(v.questionnaireNumbers,['1','2','3']);assert.equal(v.selectedChoices,3);assert.equal(v.variantTarget,'variant');assert.equal(v.badges.length,9);for(const n of ['1','2','3'])assert.equal(v.treeNumbers.filter(x=>x==='Q'+n).length,3);for(const k of ['valueOnlyUnknownVisible','variantLabels','noUnneededSelector','secondaryDraft','oneVariantQuestion','unknownVisible','failureRetained','successRetained','staleIgnored','treeRestored'])assert.equal(v[k],true,k);console.log(JSON.stringify(v,null,2));
})().catch(e=>{console.error(e);process.exitCode=1});
