// Run from the repository root with a development MV tree open and CDP enabled:
// CRL_TEST_CDP_URL=http://127.0.0.1:9258 node packages/crl-vscode/test/routeCards.browser.cjs
// Uses an isolated temporary DOM fixture; never saves an MV patch or changes content.
const esbuild=require('esbuild'),assert=require('assert/strict');
const endpoint=process.env.CRL_TEST_CDP_URL||'http://127.0.0.1:9258';
async function rpc(target,method,params){
 const ws=new WebSocket(target.webSocketDebuggerUrl);
 await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
 try{return await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('CDP timeout')),10000);ws.onmessage=e=>{const r=JSON.parse(e.data);if(r.id===1){clearTimeout(timeout);resolve(r);}};ws.send(JSON.stringify({id:1,method,params}));});}finally{ws.close();}
}
async function panes(){
 const out=[];for(const target of await(await fetch(endpoint+'/json')).json()){
  if(target.type!=='iframe')continue;
  const r=await rpc(target,'Runtime.evaluate',{expression:"document.querySelector('iframe')?.contentDocument?.body?.innerText",returnByValue:true});
  if(r.result?.result?.value)out.push({target,text:r.result.result.value});
 }return out;
}
(async()=>{
const t=(await panes()).find(p=>p.text.includes('Selected path'));
const js=esbuild.buildSync({entryPoints:['packages/crl-vscode/src/routeCardsWebview.ts'],bundle:true,write:false,format:'iife',globalName:'CardModule'}).outputFiles[0].text;
const keys=esbuild.buildSync({entryPoints:['packages/crl-vscode/src/flowKeyboardActions.ts'],bundle:true,write:false,format:'iife',globalName:'Keyboard'}).outputFiles[0].text;
const expression=`(async()=>{${js}${keys}
const d=document.querySelector('iframe').contentDocument,tree=d.createElement('div'),pane=d.createElement('div');d.body.append(tree,pane);
const style=d.createElement('style');style.nonce=d.querySelector('style[nonce]')?.nonce??'';style.textContent=CardModule.ROUTE_CARD_STYLE;d.head.append(style);
tree.innerHTML='<svg class="flow-svg" viewBox="0 0 700 500" width="700" height="500"><g data-flow-key="w" data-flow-when="w"><rect x="20" y="100" width="168" height="44"/><text data-flow-label="A complete label for the requested operation" x="30" y="122">A complete label…</text></g><g data-flow-key="q" data-flow-when="w" data-flow-parent="w" data-flow-outline="1"><rect x="35" y="180" width="150" height="34"/><g class="flow-crit-verdict"><circle cx="174" cy="189" r="8"/></g></g><g class="flow-row flow-activity flow-pinned leaf-allpass" data-flow-key="end"><rect x="240" y="100" width="168" height="44"/><g class="flow-allpass-badge"><circle r="8"/></g><g class="flow-pin"><rect x="414" y="82" width="22" height="22"/></g></g><path data-flow-from="w" data-flow-to="end" d="M188 122 L240 122"/></svg>';
tree.querySelector('[data-flow-key=q]').dataset.flowQuestion=JSON.stringify(['L','Q']);const original=tree.innerHTML;
const keyboard=Keyboard.installFlowKeyboardActions(tree);const sent=[],branchSent=[],install=(0,eval)('('+CardModule.installRouteCards.toString()+')');
const ui=install(tree,{postMessage:m=>sent.push(m)},()=>7),branch=install(pane,{postMessage:m=>branchSent.push(m)},()=>3,()=>{},true);
const payload={token:'pin',pinKey:'end',authoritativeDrafts:true,label:'Branch one',navigation:{previous:false,next:true,current:1,total:12},cards:[{id:'a',ownerKey:'w',library:'L',concept:'Q',text:'Is the requested operation documented?',description:'Description text',value:'Yes',editable:true,criterionPaths:[[]],answerChoices:[{code:'a',display:'Choice A',selected:true},{code:'b',display:'Choice B',selected:false}]}]};
const clone=x=>JSON.parse(JSON.stringify(x)),click=n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true}));ui.show(clone(payload));
const leafBox=tree.querySelector('.flow-pinned>rect').getBoundingClientRect(),verdictBox=tree.querySelector('.route-verdict-badge>circle').getBoundingClientRect();
const result={verdictTopRight:Math.abs((verdictBox.left+verdictBox.right)/2-(leafBox.right-22))<1&&Math.abs((verdictBox.top+verdictBox.bottom)/2-(leafBox.top+10))<1,oldBadgeHidden:d.defaultView.getComputedStyle(tree.querySelector('.flow-allpass-badge')).display==='none',width:tree.querySelector('.route-card').style.width,leafWidth:tree.querySelector('.flow-activity > rect').getAttribute('width'),noInlinePanel:!tree.querySelector('.route-questionnaire'),navLabel:tree.querySelector('.route-leaf-nav-label').textContent,navProgress:tree.querySelector('.route-leaf-nav-count').textContent,nextLabel:tree.querySelector('.route-branch-nav[aria-disabled=false]').getAttribute('aria-label'),navCount:tree.querySelectorAll('.route-branch-nav').length};
click(tree.querySelector('.route-branch-nav[aria-disabled=true]'));result.disabledNavigation=sent.length===0;const verdict=tree.querySelector('.route-verdict-badge');click(verdict);result.verdictMessage=sent.pop();result.verdictFocus=d.activeElement===tree.querySelector('.flow-pinned');const elsewhere=d.createElement('button');d.body.append(elsewhere);d.activeElement.blur();const scrollBefore=[d.scrollingElement.scrollLeft,d.scrollingElement.scrollTop];ui.verdictFocus({token:'pin'});await new Promise(resolve=>d.defaultView.requestAnimationFrame(resolve));result.verdictReturnFocus=d.activeElement===tree.querySelector('.flow-pinned');result.verdictNoScroll=scrollBefore.every((v,i)=>v===[d.scrollingElement.scrollLeft,d.scrollingElement.scrollTop][i]);elsewhere.focus();ui.verdictFocus({token:'old-pin'});await new Promise(resolve=>d.defaultView.requestAnimationFrame(resolve));result.staleFocusIgnored=d.activeElement===elsewhere;elsewhere.remove();click(verdict);sent.pop();const intentional=d.createElement('textarea');d.body.append(intentional);intentional.focus();ui.verdictFocus({token:'pin'});await new Promise(resolve=>d.defaultView.requestAnimationFrame(resolve));result.intentionalFocusPreserved=d.activeElement===intentional;intentional.remove();ui.verdict({token:'pin',verdict:{state:'fail',label:'Fail',count:3}});result.verdictPaint=verdict.dataset.verdict==='fail'&&verdict.getAttribute('aria-label').includes('Fail');verdict.focus();verdict.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));result.verdictEnter=sent.pop()?.type==='routeVerdictMenu';click(tree.querySelector('.route-branch-nav[aria-disabled=false]'));result.navigation=sent.pop();const nextArrow=tree.querySelector('.route-branch-nav[aria-disabled=false]');nextArrow.focus();nextArrow.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));result.enterNavigation=sent.pop()?.type==='navigatePinnedBranch';
const card=tree.querySelector('.route-card');click(card.querySelector('.route-description-toggle'));result.description=!!tree.querySelector('.route-card-description');result.descriptionFocus=d.activeElement===tree.querySelector('.route-description-toggle');
click(tree.querySelector('.route-choices-toggle'));result.choices=tree.querySelectorAll('.route-answer-choices li').length;ui.show(clone(payload));result.disclosuresSurvive=!!tree.querySelector('.route-card-description')&&tree.querySelectorAll('.route-answer-choices li').length===2;
click(tree.querySelector('.route-card-edit'));const text=tree.querySelector('textarea');text.value='Draft from attached';text.dispatchEvent(new Event('input',{bubbles:true}));
const merge=m=>{const card=payload.cards.find(c=>c.id===m.key);for(const [key,value]of Object.entries(m.fields)){if(value===null)delete card[key];else card[key]=value;}};
sent.filter(m=>m.type==='routeCardDraft').forEach(merge);sent.length=0;
click(tree.querySelector('.route-layout-toggle'));result.toggle=sent.pop();result.toggleHasNotMoved=!!tree.querySelector('.route-layout-toggle')&&!tree.querySelector('.route-questionnaire');
ui.questionnaireState(true);const qBadge=tree.querySelector(".route-question-badge").getBoundingClientRect(),qVerdict=tree.querySelector("[data-flow-key=q] .flow-crit-verdict>circle").getBoundingClientRect();result.questionClearsVerdict=qBadge.right<qVerdict.left;branch.show(clone(payload));result.separate=tree.querySelectorAll('.route-card').length===0&&pane.querySelectorAll('.route-card').length===1;result.number=pane.querySelector('.route-card-caption').textContent;result.transferredDraft=pane.querySelector('textarea').value;
const paneInput=pane.querySelector('textarea');paneInput.value='New draft from pane';paneInput.dispatchEvent(new Event('input',{bubbles:true}));const latest=branchSent.at(-1);merge(latest);ui.draft(latest);ui.questionnaireState(false);result.returnedDraft=tree.querySelector('textarea').value;
branch.reset();branch.show(clone(payload));result.reopenedDraft=pane.querySelector('textarea').value;
[...pane.querySelectorAll('.route-card-editor button')].find(n=>n.textContent==='Cancel').click();const cancelled=branchSent.at(-1);merge(cancelled);ui.draft(cancelled);ui.questionnaireState(false);branch.reset();branch.show(clone(payload));result.cancelledDraft=pane.querySelector('textarea').value;result.closedEditor=pane.querySelector('.route-card-editor').hidden;
ui.questionnaireState(true);click(pane.querySelector('.route-card-edit'));const startedInPane=branchSent.at(-1);merge(startedInPane);ui.draft(startedInPane);ui.questionnaireState(false);result.editorVisibleAfterPaneClose=!tree.querySelector('.route-card-editor').hidden;[...pane.querySelectorAll('.route-card-editor button')].find(n=>n.textContent==='Save change').click();result.proposal=branchSent.at(-1);branch.result({token:'pin',key:'a',ok:true,message:'Saved'});result.saveResult=pane.querySelector('.route-card-status').textContent;
ui.show({...clone(payload),token:'fresh',showQuestions:true});tree.querySelector('.route-questions-toggle').click();ui.show({...clone(payload),token:'fresh',showQuestions:true});result.questionsStayOff=tree.querySelector('.route-questions-toggle').getAttribute('aria-pressed')==='false';ui.show({...clone(payload),token:'new-pin',showQuestions:true});result.freshPinShowsQuestions=tree.querySelector('.route-questions-toggle').getAttribute('aria-pressed')==='true'&&!!tree.querySelector('.route-card');
const leaf=tree.querySelector('.flow-pinned');let pans=0;leaf.scrollIntoView=()=>{pans++;};click(tree.querySelector('.route-verdict-badge'));leaf.focus({preventScroll:true});
click(tree.querySelector('.route-layout-toggle'));const rqId=sent.at(-1).requestId;ui.questionnaireState(true,'new-pin',rqId);d.defaultView.dispatchEvent(new Event('resize'));await new Promise(r=>d.defaultView.setTimeout(r,210));result.questionnaireFocus=d.activeElement===leaf&&pans===1;
ui.questionnaireState(true,'new-pin',rqId);await new Promise(r=>d.defaultView.setTimeout(r,180));result.questionnaireAckNoPan=pans===1;
click(tree.querySelector('.route-layout-toggle'));ui.questionnaireState(false,'new-pin',sent.at(-1).requestId);const keep=d.createElement('textarea');d.body.append(keep);keep.focus();await new Promise(r=>d.defaultView.setTimeout(r,180));result.questionnaireKeepsEditor=d.activeElement===keep&&pans===1;keep.remove();
for(const type of ['pointerdown','wheel']){click(tree.querySelector('.route-layout-toggle'));const id=sent.at(-1).requestId;d.body.dispatchEvent(new d.defaultView.Event(type,{bubbles:true}));ui.questionnaireState(true,'new-pin',id);await new Promise(r=>d.defaultView.setTimeout(r,180));result['rqCancel_'+type]=pans===1;}
click(tree.querySelector('.route-layout-toggle'));const oldId=sent.at(-1).requestId;click(tree.querySelector('.route-layout-toggle'));const newId=sent.at(-1).requestId;ui.questionnaireState(false,'new-pin',oldId);await new Promise(r=>d.defaultView.setTimeout(r,180));result.rqOldAckIgnored=pans===1&&oldId!==newId;d.body.dispatchEvent(new d.defaultView.Event('wheel',{bubbles:true}));leaf.focus({preventScroll:true});click(tree.querySelector('.route-layout-toggle'));const crossId=sent.at(-1).requestId;const outerEditor=document.createElement('textarea');document.body.append(outerEditor);outerEditor.focus();const frameLostFocus=!d.hasFocus();ui.questionnaireState(false,'new-pin',crossId);await new Promise(r=>d.defaultView.setTimeout(r,180));result.rqCrossFramePreserved=frameLostFocus&&document.activeElement===outerEditor&&pans===1;outerEditor.remove();delete leaf.scrollIntoView;
ui.show(clone(payload));ui.questionnaireState(true);result.booleanBadge=tree.querySelector('.route-question-badge text').textContent==='Q1 Yes'&&!tree.querySelector('.route-question-form');const complex=clone(payload);complex.cards[0].value='Impairment of near or far vision due to dermatochalasis';complex.navigation={previous:true,next:false,current:12,total:12};ui.show(complex);ui.questionnaireState(true);result.complexBadge=tree.querySelector('.route-question-badge text').textContent==='Q1 …'&&tree.querySelector('.route-question-badge title').textContent.includes('See questionnaire for the full answer');result.lastProgress=tree.querySelector('.route-leaf-nav-count').textContent;const countBox=tree.querySelector('.route-leaf-nav-count').getBoundingClientRect(),prevBox=tree.querySelector('[aria-label="Previous result"]').getBoundingClientRect();result.countClear=countBox.right<prevBox.left;ui.reset();result.restored=tree.innerHTML===original;branch.reset();result.clearedPane=pane.children.length===0;keyboard.dispose();tree.remove();pane.remove();style.remove();return result;
})()`;
const r=await rpc(t.target,'Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.result.exceptionDetails)throw Error(JSON.stringify(r.result.exceptionDetails));const v=r.result.result.value;
assert.ok(v.rqCancel_pointerdown&&v.rqCancel_wheel&&v.rqOldAckIgnored);
assert.ok(v.questionnaireFocus&&v.questionnaireAckNoPan&&v.questionnaireKeepsEditor);assert.ok(v.oldBadgeHidden&&v.verdictTopRight&&v.questionClearsVerdict);assert.ok(v.verdictFocus&&v.verdictPaint&&v.verdictEnter&&v.verdictReturnFocus&&v.verdictNoScroll&&v.staleFocusIgnored&&v.intentionalFocusPreserved);assert.equal(v.verdictMessage.type,'routeVerdictMenu');assert.ok(v.questionsStayOff&&v.freshPinShowsQuestions);assert.ok(v.enterNavigation&&v.editorVisibleAfterPaneClose&&v.disclosuresSurvive);assert.equal(v.width,'320px');assert.equal(v.leafWidth,'168');assert.ok(v.noInlinePanel&&v.disabledNavigation&&v.toggleHasNotMoved&&v.separate&&v.restored&&v.clearedPane);assert.equal(v.navCount,2);assert.equal(v.navLabel,'Next');assert.equal(v.navProgress,'1 of 12');assert.equal(v.lastProgress,'12 of 12');assert.ok(v.booleanBadge&&v.complexBadge&&v.countClear);assert.equal(v.nextLabel,'Next result');assert.equal(v.navigation.type,'navigatePinnedBranch');assert.equal(v.navigation.dir,'next');assert.equal(v.toggle.type,'toggleBranchQuestionnaire');assert.equal(v.toggle.token,'pin');assert.ok(v.description&&v.descriptionFocus);assert.equal(v.choices,2);assert.equal(v.number,'1');assert.equal(v.transferredDraft,'Draft from attached');assert.equal(v.returnedDraft,'New draft from pane');assert.equal(v.reopenedDraft,'New draft from pane');assert.equal(v.cancelledDraft,'Is the requested operation documented?');assert.ok(v.closedEditor);assert.equal(v.proposal.type,'routeCardProposal');assert.equal(v.proposal.token,'pin');assert.equal(v.saveResult,'Saved');console.log(v);assert.ok(v.rqCrossFramePreserved);
})().catch(e=>{console.error(e);process.exitCode=1});
