// REFACTOR:grounded (Medical Review): compile a complete candidate before publishing any authored/generated bytes.
import { existsSync, mkdirSync, readFileSync, readdirSync, realpathSync, rmSync } from 'node:fs';
import { basename, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { buildCRL, findProjectRoot, resolveImports, emitCrlTwoLane, definitionClosureDigest, writeTwoLane,
  type DefinitionPublicationOptions } from '@smile-digital-health/crl';
import { previewPresentationFileEdit,sourceSha256 } from '@smile-digital-health/crl/language-services';
import { demotePassedReviews, loadSidecar, type MedicalValidationSidecar } from './medicalValidationStore';
import { assertOrdinaryEditPath, editTreeIdentity, readEditTree, type EditTree, type EditUnit, type TreeIdentity } from './mvEditTransaction';
import type { WordingTarget } from './presentationProposal';
import {previewAnswerChange,type AnswerTarget,type AnswerChange} from './answerEditing';

function stableJson(value: unknown):string {
  const normalized=(v:any):any=>Array.isArray(v)?v.map(normalized):v && typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,normalized(v[k])])):v;
  return JSON.stringify(normalized(value));
}
const same = (a: TreeIdentity, b: TreeIdentity) => a.kind === b.kind && a.sha256 === b.sha256;
const utf8 = (s: string) => Buffer.from(s, 'utf8');
const json = (value: unknown) => utf8(JSON.stringify(value, null, 2) + '\n');
const contains = (root: string, path: string) => {
  const r = relative(resolve(root), resolve(path)); return r !== '' && !isAbsolute(r) && r !== '..' && !r.startsWith('..' + sep);
};

export interface DirectEditCompileCache {
  discovery: Set<string>;
  snapshots: Map<string,{baseline:ReturnType<typeof emitCrlTwoLane>;candidate:ReturnType<typeof emitCrlTwoLane>}>;
}
export const createDirectEditCompileCache=():DirectEditCompileCache=>({discovery:new Set(),snapshots:new Map()});

export interface DirectEditPlan {
  projectRoot: string; publication: DefinitionPublicationOptions; projectFingerprint: string;
  definitionClosureSha256: string; baselineDefinitionClosureSha256: string;
  units: EditUnit[]; before: TreeIdentity[]; changedPaths: string[]; contentDrift: string[];
  sidecar: MedicalValidationSidecar; receiptPath: string; id: string; recheck?:()=>void; reviewWarning?:string;
}

export function recheckDirectEditInputs(plan: DirectEditPlan, target: WordingTarget, questionText: string, questionDescription: string): void {
  if(plan.recheck){plan.recheck();return;}
  const preview=previewPresentationFileEdit({projectRoot:plan.projectRoot,filePath:target.filePath},
    {library:target.library,concept:target.concept,...(target.context?{context:target.context}:{}),questionText,questionDescription});
  if (preview.projectFingerprint!==plan.projectFingerprint) throw new Error('Policy inputs changed before publication; your draft is retained.');
  plan.units.forEach((u,i)=>{if(!same(editTreeIdentity(readEditTree(u.path)),plan.before[i]))throw new Error(`Destination changed before publication: ${u.path}`);});
}

export function mvPublicationOptions(projectRoot: string): DefinitionPublicationOptions {
  const pkg = JSON.parse(readFileSync(join(projectRoot, 'package.json'), 'utf8'));
  const date = pkg.crl?.date;
  if (typeof date !== 'string' || !/^\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2}))?$/.test(date) ||
    !Number.isFinite(Date.parse(date)) || new Date(date).toISOString().slice(0, 10) !== date.slice(0, 10)) {
    throw new Error('Direct Save needs a valid configured crl.date in package.json. Repair publication metadata before editing.');
  }
  return Object.freeze({ date, capability: 'publishable' });
}

/** Complete raw authored inventory prevents registry warning/skip behavior from concealing broken local owners. */
export function authoredCrlFiles(root: string): string[] {
  const out: string[] = [];
  function walk(dir: string) {
    for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      if (entry.name.startsWith('.') || ['node_modules', 'dist', 'build'].includes(entry.name)) continue;
      const file = join(dir, entry.name);
      if (entry.isSymbolicLink()) throw new Error(`Local owner inventory includes a linked path: ${file}`);
      if (entry.isDirectory()) { if (!existsSync(join(file, 'package.json'))) walk(file); }
      else if (entry.isFile() && entry.name.endsWith('.crl')) out.push(file);
    }
  }
  walk(root); return out;
}

/** Independent entries exclude files reached through another include closure. Cycles/diagnostic failures refuse. */
export function assertSingleLocalPolicy(projectRoot: string, policyPath: string, options: DefinitionPublicationOptions): void {
  const inventory = authoredCrlFiles(projectRoot), candidates: string[] = [], included = new Set<string>();
  const libraries = new Map<string, string>(), called = new Set<string>();
  for (const file of inventory) {
    const parsed = buildCRL(readFileSync(file, 'utf8').replace(/^\uFEFF/, ''));
    if (!parsed.success || !parsed.result?.library) throw new Error(`Local CRL discovery is incomplete: ${file}`);
    libraries.set(parsed.result.library.name, file);
    // Qualified local use-decision references are supported without redundant include statements.
    function calls(value: unknown): void {
      if (!value || typeof value !== 'object') return;
      const node = value as Record<string, any>;
      if (node.type === 'UseDecision' && node.decisionName && typeof node.decisionName === 'object' && typeof node.decisionName.libraryName === 'string') {
        called.add(node.decisionName.libraryName);
      }
      for (const child of Object.values(node)) if (child && typeof child === 'object') calls(child);
    }
    calls(parsed.result);
    const graph = resolveImports(file);
    if (graph.diagnostics.some(d => d.severity === 'error' || ['parse-failure', 'registry-duplicate', 'package-resolution-failure'].includes(d.kind))) {
      throw new Error(`Local CRL discovery is incomplete: ${file}: ${JSON.stringify(graph.diagnostics)}`);
    }
    for (const library of graph.resolvedLibraries) if (resolve(library.filePath) !== resolve(file) && contains(projectRoot, library.filePath)) included.add(resolve(library.filePath));
    if (parsed.result.statements.some(s => s.type === 'Decision')) candidates.push(file);
  }
  for (const name of called) { const file = libraries.get(name); if (file) included.add(resolve(file)); }
  const roots: string[] = [];
  for (const file of candidates.filter(f => !included.has(resolve(f)))) {
    const result = emitCrlTwoLane(file, options);
    if (!result.success) throw new Error(`Cannot classify independent policy entry: ${file}`);
    const workflows = result.fhir.resources.filter(r => r.resource.resourceType === 'PlanDefinition' &&
      (r.resource.type as {coding?: {code?: string}[]} | undefined)?.coding?.some(c => c.code === 'workflow-definition'));
    if (workflows.length) roots.push(file);
  }
  if (roots.length !== 1 || relative(resolve(roots[0]), resolve(policyPath)) !== '') {
    throw new Error(`Direct Save requires one independent policy owner for src/cql and src/fhir. The KE must reconcile these entry owners: ${roots.join(', ') || 'none'}`);
  }
}

function treeFiles(tree: EditTree): ReadonlyMap<string, Uint8Array> {
  if (tree.kind === 'directory') return tree.files;
  if (tree.kind === 'missing') return new Map();
  throw new Error('A generated lane is not an ordinary directory.');
}
// Repository scaffolding is preserved in publication, but is not a generated definition.
const isScaffoldingPlaceholder = (name: string) => basename(name) === '.gitkeep';
export function generatedDefinitionDrift(live: EditTree, baseline: EditTree, directory: string) {
  const definitions = (tree: EditTree) => new Map([...treeFiles(tree)].filter(([name]) => !isScaffoldingPlaceholder(name)));
  const actual = definitions(live), expected = definitions(baseline), extra = [...actual.keys()].filter(p => !expected.has(p));
  if (extra.length) throw new Error(`Live generated files are outside this policy closure. Ask the KE to reconcile ownership; nothing will be deleted: ${extra.map(p => join(directory, p)).join(', ')}`);
  const missing = [...expected.keys()].filter(p => !actual.has(p));
  if (missing.length) throw new Error(`Generated definitions are missing. Explicitly regenerate these definitions before editing: ${missing.map(p=>join(directory,p)).join(", ")}`);
  const changed: string[] = [];
  for (const [name, bytes] of actual) {
    if (!Buffer.from(bytes).equals(Buffer.from(expected.get(name)!))) {
      if (name.endsWith('.json')) {
        const a = JSON.parse(Buffer.from(bytes).toString('utf8')), b = JSON.parse(Buffer.from(expected.get(name)!).toString('utf8'));
        const publication = (r: any) => JSON.stringify({date:r.date,profile:r.meta?.profile,capability:r.extension?.filter((e:any)=>e.url?.includes('knowledgeCapability'))});
        if (publication(a) !== publication(b)) throw new Error(`Publication fields differ in ${join(directory, name)}. Reconcile configured definition publication before direct editing.`);
      }
      changed.push(join(directory, name));
    }
  }
  return changed;
}

function changedMembers(path: string, before: EditTree, after: EditTree): string[] {
  if (same(editTreeIdentity(before), editTreeIdentity(after))) return [];
  if (before.kind !== 'directory' && after.kind !== 'directory') return [path];
  const a = treeFiles(before), b = treeFiles(after);
  return [...new Set([...a.keys(), ...b.keys()])].filter(k => !a.has(k) || !b.has(k) ||
    !Buffer.from(a.get(k)!).equals(Buffer.from(b.get(k)!))).sort().map(k => join(path, k));
}

/** Pure live-tree planning; scratch is isolated local recovery storage, never a live generated writer. */
interface QuestionEditOptions { policyPath: string; target: WordingTarget; questionText: string;
  questionDescription: string; sidecarPath: string; id: string; editedAt: string;
  scratchRoot: string; compileCache?: DirectEditCompileCache; planningBoundary?: (point:"before-final-preview")=>void; acquired?: readonly string[]; preExisting?: readonly string[] }

export function planDirectQuestionEdit(options:QuestionEditOptions):DirectEditPlan {return planDirectSourceEdit(options);}
export function planDirectAnswerEdit(options:Omit<QuestionEditOptions,"target"|"questionText"|"questionDescription"> & {target:AnswerTarget;change:AnswerChange}):DirectEditPlan {
  const t=options.target;
  const target:WordingTarget={filePath:t.filePath,library:t.library,concept:t.terminology,baseline:t.baseline,questionText:t.terminology,questionDescription:"",scopeLabel:"Answer terminology",owners:{},editable:t.editable,readOnlyReason:t.readOnlyReason};
  return planDirectSourceEdit({...options,target,questionText:t.terminology,questionDescription:"",sourceEdit:()=>previewAnswerChange(options.policyPath,t,options.change)});
}
function planDirectSourceEdit(options:QuestionEditOptions & {sourceEdit?:()=>ReturnType<typeof previewAnswerChange>}):DirectEditPlan {
  const { target } = options, projectRoot = findProjectRoot(options.policyPath);
  if (!projectRoot) throw new Error('The selected policy has no package owner.');
  if(!contains(join(projectRoot,'src/crl'),options.policyPath) || resolve(options.sidecarPath)!==resolve(projectRoot,'src/medical-validation',basename(projectRoot)+'.json'))throw new Error('Direct Save layout requires the policy under artifact/src/crl and review state at artifact/src/medical-validation/<artifact-name>.json. Open the owning artifact package.');
  if (target.editable === false) throw new Error(target.readOnlyReason ?? 'This question is read-only.');
  if (!contains(projectRoot, target.filePath) || !contains(projectRoot, options.sidecarPath)) throw new Error('Question/review state belongs to another project.');

  if (!options.questionText.trim() || options.questionText.length > 8000 || options.questionDescription.length > 16000) throw new Error('Question wording is empty or exceeds the editing limit.');
  const sidecarTree=readEditTree(options.sidecarPath), sourceTree=readEditTree(target.filePath);
  if(sourceTree.kind!=="file" || Buffer.from(sourceTree.bytes).toString("utf8")!==target.baseline)throw new Error("The question source changed. Re-pin before saving; your draft is retained.");
  const sidecarBefore = editTreeIdentity(sidecarTree);
  const loaded = loadSidecar(options.sidecarPath);
  if (loaded.warning) throw new Error(`Review sidecar needs repair: ${loaded.warning}`);
  if (!same(sidecarBefore, editTreeIdentity(readEditTree(options.sidecarPath)))) throw new Error("Review sidecar changed during capture.");
  const priorReview = loaded.sidecar;
  if(sidecarTree.kind==='file'){
    const raw=JSON.parse(Buffer.from(sidecarTree.bytes).toString('utf8'));
    const normalized=structuredClone(raw);
    if(normalized.schemaVersion===1){normalized.schemaVersion=2;for(const id of Object.keys(normalized.byCaseId??{}))if(normalized.byCaseId[id]==='reviewed')normalized.byCaseId[id]='pass';}
    for(const field of ['notesByCaseId','criterionVerdictsByKey'])if(normalized[field] && typeof normalized[field]==='object' && !Array.isArray(normalized[field]) && !Object.keys(normalized[field]).length)delete normalized[field];
    if(stableJson(normalized)!==stableJson(priorReview))throw new Error('Review sidecar needs repair: normalization would discard or change stored review information. No edits were made.');
  }
  const publication = mvPublicationOptions(projectRoot);
  const request = {library:target.library,concept:target.concept,...(target.context ? {context:target.context}:{}),questionText:options.questionText,questionDescription:options.questionDescription};
  const getPreview=()=>{
    if(options.sourceEdit)return options.sourceEdit();
    const p=previewPresentationFileEdit({projectRoot,filePath:target.filePath},request);
    return {...p,sourceOverlays:new Map([[target.filePath,p.candidateSource]]),sources:new Map([[target.filePath,p.source]]),answerReceipt:undefined,caseFingerprint:undefined};
  };
  const preview=getPreview();
  const key=JSON.stringify([projectRoot,options.policyPath,preview.projectFingerprint,preview.afterSha256,publication]);
  const cache=options.compileCache;
  if(!cache?.discovery.has(key)){assertSingleLocalPolicy(projectRoot, options.policyPath, publication);cache?.discovery.add(key);}
  let snapshot=cache?.snapshots.get(key);
  if(!snapshot){snapshot={baseline:emitCrlTwoLane(options.policyPath, publication),candidate:emitCrlTwoLane(options.policyPath, {...publication,sourceOverlays:preview.sourceOverlays})};cache?.snapshots.set(key,snapshot);}
  const {baseline,candidate}=snapshot;
  const workflows = candidate.fhir.resources.filter(r => r.resource.resourceType === 'PlanDefinition' &&
    (r.resource.type as {coding?:{code?:string}[]} | undefined)?.coding?.some(c=>c.code==='workflow-definition'));
  if (!baseline.success || !candidate.success || !candidate.cql.success || workflows.length !== 1) throw new Error('The complete policy definition candidate did not emit successfully. No live bytes changed.');
  const digest = definitionClosureDigest(candidate)!, beforeDigest = definitionClosureDigest(baseline)!;
  const receiptPath = join(projectRoot,'src/medical-validation/direct-edits',`${options.id}.json`);
  if (existsSync(receiptPath)) throw new Error('An edit receipt already exists for this transaction.');
  const sidecar = demotePassedReviews(priorReview,{id:options.id,definitionClosureSha256:digest,editedAt:options.editedAt,receiptPath:relative(projectRoot,receiptPath).replace(/\\/g,'/')});
  const units: EditUnit[] = [...preview.sourceOverlays].filter(([file,text])=>preview.sources.get(file)!==text).map(([path,text])=>({path,after:{kind:'file',bytes:utf8(text)}}));
  const capturedBefore=new Map<string,EditTree>([[options.sidecarPath,sidecarTree],[receiptPath,{kind:'missing'}]]);
  for(const [file,text] of preview.sources){const before=readEditTree(file);if(before.kind!=='file' || Buffer.from(before.bytes).toString('utf8')!==text)throw new Error('Answer source changed during capture.');capturedBefore.set(file,before);}
  const scratchRoot=resolve(options.scratchRoot);
  assertOrdinaryEditPath(scratchRoot);
  const scratch = resolve(scratchRoot,options.id);
  if (contains(projectRoot,scratch) || projectRoot===scratch || !/^[a-f0-9-]{36}$/.test(options.id)) throw new Error('Scratch must be outside the project with a valid transaction identity.');
  if (existsSync(scratch)) throw new Error('Edit scratch already exists.');
  mkdirSync(scratchRoot,{recursive:true});assertOrdinaryEditPath(scratchRoot);
  const scratchOwner=realpathSync(scratchRoot);
  mkdirSync(scratch);
  const drift: string[] = [];
  try {
    writeTwoLane(baseline,join(scratch,'baseline/src'));writeTwoLane(candidate,join(scratch,'candidate/src'));
    for (const lane of ['cql','fhir']) {
      const path=join(projectRoot,'src',lane),before=readEditTree(path),expected=readEditTree(join(scratch,'baseline/src',lane)),after=readEditTree(join(scratch,'candidate/src',lane));
      drift.push(...generatedDefinitionDrift(before,expected,path));capturedBefore.set(path,before);
      // The transaction replaces the whole lane; retain every live placeholder's exact path and bytes.
      const files=new Map(treeFiles(after));
      for(const [name,bytes] of treeFiles(before))if(isScaffoldingPlaceholder(name))files.set(name,bytes);
      units.push({path,after:{...after,kind:'directory',files}});
    }
    units.push({path:options.sidecarPath,after:{kind:'file',bytes:json(sidecar)}});
    units.push({path:receiptPath,after:{kind:'file',bytes:json({schemaVersion:1,id:options.id,kind:'medical-review-direct-edit',editedAt:options.editedAt,
      owner:{file:relative(projectRoot,target.filePath).replace(/\\/g,'/'),library:target.library,concept:target.concept,context:target.context},
      ...(preview.answerReceipt ? {answers:{...preview.answerReceipt,resources:{before:baseline.fhir.resources.filter(r=>r.resourceType==='ValueSet' && r.sourceName===target.concept || r.resourceType==='CodeSystem' && r.resource.url===(preview.answerReceipt!.before?.system ?? preview.answerReceipt!.after?.system)).map(r=>({resourceType:r.resourceType,id:r.resource.id,url:r.resource.url})),after:candidate.fhir.resources.filter(r=>r.resourceType==='ValueSet' && r.sourceName===target.concept || r.resourceType==='CodeSystem' && r.resource.url===(preview.answerReceipt!.before?.system ?? preview.answerReceipt!.after?.system)).map(r=>({resourceType:r.resourceType,id:r.resource.id,url:r.resource.url}))}},sources:[...preview.sources].map(([file,text])=>({file:relative(projectRoot,file).replace(/\\/g,"/"),before:text,after:preview.sourceOverlays.get(file),beforeSha256:sourceSha256(text),afterSha256:sourceSha256(preview.sourceOverlays.get(file)!)}))} : {}),
      wording:{before:{questionText:target.questionText,questionDescription:target.questionDescription},after:{questionText:options.questionText,questionDescription:options.questionDescription}},
      source:{before:preview.beforeSha256,after:preview.afterSha256},definitions:{before:beforeDigest,after:digest},publication,
      priorReview,priorReviewSource:sidecarTree.kind==='file'?Buffer.from(sidecarTree.bytes).toString('utf8'):null,contentDrift:drift.map(p=>relative(projectRoot,p).replace(/\\/g,'/')),acquired:options.acquired??[],preExisting:options.preExisting??[]})}});
  } finally {
    // Resolved scratch was checked outside the project and is a direct UUID child of the supplied local storage.
    assertOrdinaryEditPath(scratch);
    if(realpathSync(scratchRoot)!==scratchOwner || realpathSync(scratch)!==join(scratchOwner,options.id))throw new Error('Scratch ownership changed; temporary files retained for inspection.');
    rmSync(scratch,{recursive:true,force:true});
  }
  if (!same(sidecarBefore, editTreeIdentity(readEditTree(options.sidecarPath)))) throw new Error("Review sidecar changed during planning; re-pin before saving.");
  options.planningBoundary?.("before-final-preview");
  const afterPreview=getPreview();
  if (afterPreview.projectFingerprint !== preview.projectFingerprint || afterPreview.caseFingerprint!==preview.caseFingerprint) throw new Error('Project inputs changed during candidate planning.');
  const changedUnits=units.filter(u=>!same(editTreeIdentity(capturedBefore.get(u.path)!),editTreeIdentity(u.after)));
  for(const unit of units)if(!same(editTreeIdentity(capturedBefore.get(unit.path)!),editTreeIdentity(readEditTree(unit.path))))throw new Error(`Destination changed during planning: ${unit.path}`);
  return { projectRoot,publication,projectFingerprint:preview.projectFingerprint,definitionClosureSha256:digest,baselineDefinitionClosureSha256:beforeDigest,
    units:changedUnits,before:changedUnits.map(u=>editTreeIdentity(capturedBefore.get(u.path)!)),changedPaths:changedUnits.flatMap(u=>changedMembers(u.path,capturedBefore.get(u.path)!,u.after)),
    contentDrift:drift,sidecar,receiptPath,id:options.id,reviewWarning:preview.answerReceipt?.caseImpact.length ? 'Answer applied. Existing examples are stale and unrunnable until repaired: '+preview.answerReceipt.caseImpact.map(c=>c.file+': '+c.message).join('; ') : undefined,recheck:()=>{
      const current=getPreview();if(current.projectFingerprint!==preview.projectFingerprint || current.caseFingerprint!==preview.caseFingerprint)throw new Error('Policy inputs changed before publication; your draft is retained.');
      changedUnits.forEach(u=>{if(!same(editTreeIdentity(readEditTree(u.path)),editTreeIdentity(capturedBefore.get(u.path)!)))throw new Error(`Destination changed before publication: ${u.path}`);});
    } };
}
