/** Static shell. Authored values arrive through postMessage and are assigned as text, never HTML. */
export function presentationEditorHtml(nonce: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}';"><meta name="viewport" content="width=device-width, initial-scale=1"><style nonce="${nonce}">
body{font:var(--vscode-font-size) var(--vscode-font-family);color:var(--vscode-foreground);padding:20px;max-width:800px}h1{font-size:1.3em}label{display:block;margin:18px 0 5px;font-weight:600}textarea{box-sizing:border-box;width:100%;resize:vertical;color:var(--vscode-input-foreground);background:var(--vscode-input-background);border:1px solid var(--vscode-input-border,transparent);padding:9px;font:inherit}button{padding:7px 12px;margin:12px 6px 0 0;border:0;color:var(--vscode-button-foreground);background:var(--vscode-button-background);cursor:pointer}button.secondary{color:var(--vscode-button-secondaryForeground);background:var(--vscode-button-secondaryBackground)}button:disabled{opacity:.45;cursor:default}button:focus-visible,textarea:focus-visible{outline:1px solid var(--vscode-focusBorder)}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit;margin:12px 0;padding:12px;background:var(--vscode-textCodeBlock-background)}.muted{color:var(--vscode-descriptionForeground)}[hidden]{display:none!important}#status{margin-top:16px}#scope{font-weight:600}
</style></head><body><h1>Edit Question Wording</h1><p id="identity"></p><p id="scope"></p><p class="muted">Edits the owning CRL source. Shared default wording can affect multiple uses.</p><label for="question">Question</label><textarea id="question" rows="3" maxlength="8000" disabled></textarea><label for="description">Description</label><textarea id="description" rows="5" maxlength="16000" disabled></textarea><p class="muted">Clear the description to request removal. Untouched fields stay unchanged.</p><button id="preview" disabled>Preview</button><button id="diff" class="secondary" disabled>Show source diff</button><button id="apply" disabled>Apply source edit</button><div id="status" role="status" aria-live="polite"></div><pre id="summary" hidden></pre><div id="conflict" hidden><button id="current" class="secondary">Use current wording</button><button id="keep">Keep my draft</button></div><script nonce="${nonce}">
const api=acquireVsCodeApi();const el=id=>document.getElementById(id);let token=null,revision=0,initialized=false;
const values=()=>({questionText:el('question').value,questionDescription:el('description').value});
const update=v=>{el('question').value=v.questionText;el('description').value=v.questionDescription;};
const invalidate=()=>{token=null;el('apply').disabled=true;el('diff').disabled=true;el('conflict').hidden=true;};
for(const id of ['question','description'])el(id).addEventListener('input',()=>{if(!initialized)return;revision++;invalidate();el('status').textContent='Preview your changed draft.';});
el('preview').onclick=()=>{if(!initialized)return;revision++;invalidate();el('status').textContent='Checking source and scope...';api.postMessage({kind:'preview',revision,...values()});};
el('diff').onclick=()=>{if(initialized&&token)api.postMessage({kind:'diff',revision});};
el('apply').onclick=()=>{if(!initialized||!token)return;el('apply').disabled=true;api.postMessage({kind:'apply',revision,token,...values()});};
for(const [id,choice] of [['current','current'],['keep','draft']])el(id).onclick=()=>{if(initialized)api.postMessage({kind:'resolve',revision:++revision,choice,...values()});};
window.addEventListener('message',event=>{const m=event.data;
if(m.revision!==undefined&&m.revision!==revision){if(m.kind==='applied')el('status').textContent='Earlier preview applied. Preview your current draft before applying it.';return;}
if(m.baselineId)api.postMessage({kind:'ack',revision,baselineId:m.baselineId});
if(m.values)update(m.values);
if(m.kind==='ready'){initialized=true;el('preview').disabled=false;el('question').disabled=false;el('description').disabled=false;el('identity').textContent=m.title;el('scope').textContent=m.scope;return;}
if(m.kind==='preview'){token=m.token;el('diff').disabled=false;el('apply').disabled=false;el('conflict').hidden=true;el('summary').hidden=false;el('summary').textContent=m.fields.map(f=>f.field+': '+JSON.stringify(f.before)+' → '+JSON.stringify(f.proposed)).join('\\n\\n')+'\\n\\n'+m.impact.map(i=>i.field+': '+i.scope+'\\n'+i.externalConsumers).join('\\n\\n')+'\\n\\nChecks: '+m.validation.coverage+'\\nStill required: '+m.validation.remaining.join('; ');el('status').textContent='Review the scope and source diff, then apply.';return;}
if(m.kind==='conflict'){invalidate();el('conflict').hidden=false;el('summary').hidden=false;el('summary').textContent=m.conflicts.map(c=>c.field+' changed'+(c.ownerChanged?' (owner scope changed)':'')+'\\nOriginal: '+JSON.stringify(c.before)+'\\nCurrent: '+JSON.stringify(c.current)+'\\nYour draft: '+JSON.stringify(c.proposed)).join('\\n\\n');el('status').textContent='Source changed in a field you edited. Choose how to re-preview.';return;}
invalidate();el('status').textContent=m.message||'';if(m.kind==='applied'||m.kind==='draft')el('summary').hidden=true;
});api.postMessage({kind:'ready',revision});
</script></body></html>`;
}
